import {useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useAuth} from '../context/AuthContext';
import {api} from '../api';

export default function Login(){
  const {login,setUser}=useAuth(),nav=useNavigate();
  const [register,setRegister]=useState(false),[form,setForm]=useState({email:'',password:'',name:'',role:'advertiser',company:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const set=(key,value)=>setForm(current=>({...current,[key]:value}));
  const submit=async event=>{event.preventDefault();setBusy(true);setError('');try{if(register){const result=await api.post('/auth/register',form);localStorage.setItem('token',result.data.token);setUser(result.data.user)}else{await login(form)}nav('/')}catch(e){setError(e.response?.data?.message||'Unable to continue')}finally{setBusy(false)}};
  return <div className="grid min-h-screen bg-slate-950 lg:grid-cols-2"><section className="hidden bg-brand p-14 text-white lg:block"><p className="text-3xl font-bold">adpulse</p><div className="mt-40"><h1 className="text-5xl font-bold leading-tight">Campaigns that make every impression count.</h1><p className="mt-6 max-w-md text-lg text-indigo-100">Plan, launch, monitor and optimize your digital advertising from one focused workspace.</p></div></section><section className="grid place-items-center p-5 sm:p-8"><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl sm:p-8"><h2 className="text-2xl font-bold">{register?'Create your account':'Welcome back'}</h2><p className="mt-2 text-sm text-slate-500">{register?'Join as an advertiser or publisher.':'Enter your account details to continue.'}</p>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}{register&&<><label>Full name<input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label>Company<input value={form.company} onChange={e=>set('company',e.target.value)}/></label><label>Account type<select value={form.role} onChange={e=>set('role',e.target.value)}><option value="advertiser">Advertiser</option><option value="publisher">Publisher</option></select></label></>}<label>Email address<input required type="email" autoComplete="email" value={form.email} onChange={e=>set('email',e.target.value)} placeholder="you@example.com"/></label><label>Password<input required minLength="6" type="password" autoComplete={register?'new-password':'current-password'} value={form.password} onChange={e=>set('password',e.target.value)} placeholder="At least 6 characters"/></label><button disabled={busy} className="btn mt-5 w-full">{busy?'Please wait…':register?'Create account':'Sign in'}</button><button type="button" onClick={()=>{setRegister(!register);setError('')}} className="mt-5 w-full text-sm font-medium text-brand">{register?'Already registered? Sign in':'Need an account? Register'}</button></form></section></div>;
}
