import express from 'express'; import Campaign from '../models/Campaign.js'; import Notification from '../models/Notification.js'; import FraudEvent from '../models/FraudEvent.js'; import {protect} from '../middleware/auth.js';
const router=express.Router();
router.get('/dashboard',protect,async(req,res)=>{const q=req.user.role==='advertiser'?{advertiser:req.user.id}:{};const campaigns=await Campaign.find(q);const totals=campaigns.reduce((a,c)=>({impressions:a.impressions+c.impressions,clicks:a.clicks+c.clicks,spent:a.spent+c.spent,budget:a.budget+c.budget}),{impressions:0,clicks:0,spent:0,budget:0});const series=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day=>({day,impressions:0,clicks:0,spent:0}));res.json({...totals,ctr:totals.impressions?Number((totals.clicks/totals.impressions*100).toFixed(2)):0,campaigns,series})});
router.get('/notifications',protect,async(req,res)=>res.json(await Notification.find({user:req.user.id}).sort('-createdAt').limit(30)));
router.patch('/notifications/:id/read',protect,async(req,res)=>res.json(await Notification.findOneAndUpdate({_id:req.params.id,user:req.user.id},{read:true},{new:true})));
router.get('/fraud',protect,async(req,res)=>res.json(await FraudEvent.find().populate('campaign','name').sort('-createdAt')));
router.post('/assistant',protect,async(req,res)=>{const topic=req.body.prompt||'';const sport=/sport|event|match|tournament/i.test(topic);res.json({title:sport?'Drive registrations for your sports event':'High-intent audience campaign',description:`A focused campaign created from: ${topic}`,targetAudience:sport?'Sports fans aged 18–40 near the event venue':'Adults aged 25–45 with relevant interests',keywords:sport?['sports event','tickets','local tournament','live match']:['brand awareness','online campaign','customer acquisition'],estimatedCTR:sport?'3.2%':'2.4%',recommendation:'Start with 2–3 visual variants and reserve 20% of budget for retargeting.'})});
router.get('/report',protect,async(req,res)=>{const q=req.user.role==='advertiser'?{advertiser:req.user.id}:{};const campaigns=await Campaign.find(q);const t=campaigns.reduce((a,c)=>({impressions:a.impressions+c.impressions,clicks:a.clicks+c.clicks,spent:a.spent+c.spent}),{impressions:0,clicks:0,spent:0});res.json({generatedAt:new Date(),...t,ctr:t.impressions?Number((t.clicks/t.impressions*100).toFixed(2)):0,cpc:t.clicks?Number((t.spent/t.clicks).toFixed(2)):0,campaigns})});
export default router;
