import express from 'express'; import PublisherSite from '../models/PublisherSite.js'; import {protect,allow} from '../middleware/auth.js';
const router=express.Router();
const adCodeFor = site => { const adServer=(process.env.AD_SERVER_URL||`http://localhost:${process.env.PORT||5000}`).replace(/\/$/,''); return `<script async src="${adServer}/api/ads/adpulse.js" data-site="${site.id}"></script>`; };
router.get('/sites',protect,allow('publisher'),async(req,res)=>{const sites=await PublisherSite.find({publisher:req.user.id}).sort('-createdAt');res.json(sites.map(site=>({...site.toJSON(),adCode:adCodeFor(site)})))});
router.post('/sites',protect,allow('publisher'),async(req,res)=>{const site=await PublisherSite.create({...req.body,publisher:req.user.id});site.adCode=adCodeFor(site);await site.save();res.status(201).json(site)});
router.patch('/sites/:id',protect,allow('publisher'),async(req,res)=>{const site=await PublisherSite.findOne({_id:req.params.id,publisher:req.user.id});if(!site)return res.status(404).json({message:'Site not found'});['name','url'].forEach(key=>{if(req.body[key]!==undefined)site[key]=req.body[key]});if(req.body.name!==undefined||req.body.url!==undefined)site.status='pending';await site.save();res.json(site)});
router.delete('/sites/:id',protect,allow('publisher'),async(req,res)=>{const site=await PublisherSite.findOneAndDelete({_id:req.params.id,publisher:req.user.id});if(!site)return res.status(404).json({message:'Site not found'});res.status(204).end()});
router.get('/summary',protect,allow('publisher'),async(req,res)=>{const sites=await PublisherSite.find({publisher:req.user.id});const totals=sites.reduce((a,s)=>({impressions:a.impressions+s.impressions,clicks:a.clicks+s.clicks,earnings:a.earnings+s.earnings}),{impressions:0,clicks:0,earnings:0});res.json({...totals,ctr:totals.impressions?Number((totals.clicks/totals.impressions*100).toFixed(2)):0,activeAds:sites.filter(s=>s.status==='approved').length,sites})});
export default router;
